// <auto-generated />
using System;
using HappyHome.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyHome.Infrastructure.Migrations
{
    [DbContext(typeof(HappyHomeDbContext))]
    [Migration("20260523132425_AddAnvändare")]
    partial class AddAnvändare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyHome.Core.Models.Användare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("LösenordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TerapeutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Epost")
                        .IsUnique();

                    b.HasIndex("KlientId");

                    b.HasIndex("TerapeutId");

                    b.ToTable("Användare");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnledningTillBesok")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TerapiTyp")
                        .HasColumnType("int");

                    b.Property<int>("TidsluckaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("TidsluckaId")
                        .IsUnique();

                    b.ToTable("Bokningar");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Födelsedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Epost")
                        .IsUnique();

                    b.HasIndex("Personnummer")
                        .IsUnique();

                    b.ToTable("Klienter");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Konsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anteckningar")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Bakgrund")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("BokningId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosförslag")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symptom")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TerapeutId")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BokningId")
                        .IsUnique()
                        .HasFilter("[BokningId] IS NOT NULL");

                    b.HasIndex("KlientId");

                    b.HasIndex("TerapeutId");

                    b.ToTable("Konsultationer");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Terapeut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AktivFromDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Roll")
                        .HasColumnType("int");

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialiseringar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Epost")
                        .IsUnique();

                    b.ToTable("Terapeuter");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Tidslucka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Skapad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Slut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TerapeutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerapeutId", "Start");

                    b.ToTable("Tidsluckor");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Användare", b =>
                {
                    b.HasOne("HappyHome.Core.Models.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappyHome.Core.Models.Terapeut", "Terapeut")
                        .WithMany()
                        .HasForeignKey("TerapeutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Klient");

                    b.Navigation("Terapeut");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Bokning", b =>
                {
                    b.HasOne("HappyHome.Core.Models.Klient", "Klient")
                        .WithMany("Bokningar")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyHome.Core.Models.Tidslucka", "Tidslucka")
                        .WithOne("Bokning")
                        .HasForeignKey("HappyHome.Core.Models.Bokning", "TidsluckaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Tidslucka");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Konsultation", b =>
                {
                    b.HasOne("HappyHome.Core.Models.Bokning", "Bokning")
                        .WithOne("Konsultation")
                        .HasForeignKey("HappyHome.Core.Models.Konsultation", "BokningId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HappyHome.Core.Models.Klient", "Klient")
                        .WithMany("Konsultationer")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyHome.Core.Models.Terapeut", "Terapeut")
                        .WithMany("Konsultationer")
                        .HasForeignKey("TerapeutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bokning");

                    b.Navigation("Klient");

                    b.Navigation("Terapeut");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Tidslucka", b =>
                {
                    b.HasOne("HappyHome.Core.Models.Terapeut", "Terapeut")
                        .WithMany("Tidsluckor")
                        .HasForeignKey("TerapeutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeut");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Bokning", b =>
                {
                    b.Navigation("Konsultation");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Klient", b =>
                {
                    b.Navigation("Bokningar");

                    b.Navigation("Konsultationer");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Terapeut", b =>
                {
                    b.Navigation("Konsultationer");

                    b.Navigation("Tidsluckor");
                });

            modelBuilder.Entity("HappyHome.Core.Models.Tidslucka", b =>
                {
                    b.Navigation("Bokning");
                });
#pragma warning restore 612, 618
        }
    }
}
